# 🎮 SteamSense

# 01 - Data Loading

## Objective

Load and inspect the Steam recommendation dataset before preprocessing.

### Datasets

- games.csv
- users.csv
- recommendations.csv
- games_metadata.json

### Goals

- Load datasets
- Inspect columns
- Check data types
- Understand relationships
- Prepare for cleaning

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

In [2]:
DATA_PATH = Path("../data/raw")

In [3]:
games = pd.read_csv(DATA_PATH / "games.csv")
users = pd.read_csv(DATA_PATH / "users.csv")
recommendations = pd.read_csv(DATA_PATH / "recommendations.csv")

C:\Users\Vedant\AppData\Local\Temp\ipykernel_26000\1148545940.py:3: DtypeWarning: Columns (0: is_recommended) have mixed types. Specify dtype option on import or set low_memory=False.
  recommendations = pd.read_csv(DATA_PATH / "recommendations.csv")

In [4]:
with open(DATA_PATH / "games_metadata.json", "r", encoding="utf-8") as file:
    metadata = file.read()

print("Metadata loaded successfully.")

Metadata loaded successfully.

In [5]:
print("Games Dataset:", games.shape)
print("Users Dataset:", users.shape)
print("Recommendations Dataset:", recommendations.shape)

Games Dataset: (50872, 13)
Users Dataset: (0, 1)
Recommendations Dataset: (29200464, 8)

In [6]:
games.head()

,app_id,title,date_release,win,mac,linux,rating,positive_ratio,user_reviews,price_final,price_original,discount,steam_deck
0,13500,Prince of Persia: Warrior Within™,2008-11-21,True,False,False,Very Positive,84,2199,9.99,9.99,0.0,True
1,22364,BRINK: Agents of Change,2011-08-03,True,False,False,Positive,85,21,2.99,2.99,0.0,True
2,113020,Monaco: What's Yours Is Mine,2013-04-24,True,True,True,Very Positive,92,3722,14.99,14.99,0.0,True
3,226560,Escape Dead Island,2014-11-18,True,False,False,Mixed,61,873,14.99,14.99,0.0,True
4,249050,Dungeon of the ENDLESS™,2014-10-27,True,True,False,Very Positive,88,8784,11.99,11.99,0.0,True

In [7]:
users.head()

Empty DataFrame
Columns: [Unnamed: 0]
Index: []

In [8]:
recommendations.head()

,app_id,helpful,funny,date,is_recommended,hours,user_id,review_id
0,975370,0.0,0.0,2022-12-12,True,36.3,51580.0,0.0
1,304390,4.0,0.0,2017-02-17,False,11.5,2586.0,1.0
2,1085660,2.0,0.0,2019-11-17,True,336.5,253880.0,2.0
3,703080,0.0,0.0,2022-09-23,True,27.4,259432.0,3.0
4,526870,0.0,0.0,2021-01-10,True,7.9,23869.0,4.0

In [9]:
games.columns.tolist()

['app_id',
 'title',
 'date_release',
 'win',
 'mac',
 'linux',
 'rating',
 'positive_ratio',
 'user_reviews',
 'price_final',
 'price_original',
 'discount',
 'steam_deck']

In [10]:
users.columns.tolist()

['Unnamed: 0']

In [11]:
recommendations.columns.tolist()

['app_id',
 'helpful',
 'funny',
 'date',
 'is_recommended',
 'hours',
 'user_id',
 'review_id']

In [12]:
games.info()

<class 'pandas.DataFrame'>
RangeIndex: 50872 entries, 0 to 50871
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   app_id          50872 non-null  int64
 1   title           50872 non-null  str
 2   date_release    50872 non-null  str
 3   win             50872 non-null  bool
 4   mac             50872 non-null  bool
 5   linux           50872 non-null  bool
 6   rating          50872 non-null  str
 7   positive_ratio  50872 non-null  int64
 8   user_reviews    50872 non-null  int64
 9   price_final     50872 non-null  float64
 10  price_original  50872 non-null  float64
 11  discount        50872 non-null  float64
 12  steam_deck      50872 non-null  bool
dtypes: bool(4), float64(3), int64(3), str(3)
memory usage: 3.7 MB

In [13]:
users.info()

<class 'pandas.DataFrame'>
RangeIndex: 0 entries
Data columns (total 1 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  0 non-null      object
dtypes: object(1)
memory usage: 132.0+ bytes

In [14]:
recommendations.info()

<class 'pandas.DataFrame'>
RangeIndex: 29200464 entries, 0 to 29200463
Data columns (total 8 columns):
 #   Column          Dtype
---  ------          -----
 0   app_id          int64
 1   helpful         float64
 2   funny           float64
 3   date            str
 4   is_recommended  object
 5   hours           float64
 6   user_id         float64
 7   review_id       float64
dtypes: float64(5), int64(1), object(1), str(1)
memory usage: 1.7+ GB

In [15]:
games.describe(include="all")

,app_id,title,date_release,win,mac,linux,rating,positive_ratio,user_reviews,price_final,price_original,discount,steam_deck
count,5.087200e+04,50872,50872,50872,50872,50872,50872,50872.000000,5.087200e+04,50872.000000,50872.000000,50872.000000,50872
unique,NaN,50751,4292,2,2,2,9,NaN,NaN,NaN,NaN,NaN,2
top,NaN,Loop,2020-06-18,True,False,False,Positive,NaN,NaN,NaN,NaN,NaN,True
freq,NaN,4,92,50076,37854,41831,13502,NaN,NaN,NaN,NaN,NaN,50870
mean,1.055224e+06,NaN,NaN,NaN,NaN,NaN,NaN,77.052033,1.824425e+03,8.620325,8.726788,5.592212,NaN
std,6.103249e+05,NaN,NaN,NaN,NaN,NaN,NaN,18.253592,4.007352e+04,11.514164,11.507021,18.606679,NaN
min,1.000000e+01,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000e+01,0.000000,0.000000,0.000000,NaN
25%,5.287375e+05,NaN,NaN,NaN,NaN,NaN,NaN,67.000000,1.900000e+01,0.990000,0.990000,0.000000,NaN
50%,9.860850e+05,NaN,NaN,NaN,NaN,NaN,NaN,81.000000,4.900000e+01,4.990000,4.990000,0.000000,NaN
75%,1.524895e+06,NaN,NaN,NaN,NaN,NaN,NaN,91.000000,2.060000e+02,10.990000,11.990000,0.000000,NaN
max,2.599300e+06,NaN,NaN,NaN,NaN,NaN,NaN,100.000000,7.494460e+06,299.990000,299.990000,90.000000,NaN

In [16]:
users.describe(include="all")

       Unnamed: 0
count           0
unique          0
top           NaN
freq          NaN

In [17]:
recommendations.describe(include="all")

,app_id,helpful,funny,date,is_recommended,hours,user_id,review_id
count,2.920046e+07,2.920046e+07,2.920046e+07,29200463,29200463,2.920046e+07,2.920046e+07,2.920046e+07
unique,NaN,NaN,NaN,4449,2,NaN,NaN,NaN
top,NaN,NaN,NaN,2019-06-29,True,NaN,NaN,NaN
freq,NaN,NaN,NaN,145406,25138527,NaN,NaN,NaN
mean,5.959795e+05,3.345878e+00,1.141334e+00,NaN,NaN,1.198385e+02,7.415959e+06,1.460023e+07
std,4.672061e+05,5.253659e+01,3.170325e+01,NaN,NaN,1.893659e+02,4.035869e+06,8.429448e+06
min,1.000000e+01,0.000000e+00,0.000000e+00,NaN,NaN,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.524900e+05,0.000000e+00,0.000000e+00,NaN,NaN,1.190000e+01,4.184872e+06,7.300116e+06
50%,4.333400e+05,0.000000e+00,0.000000e+00,NaN,NaN,3.920000e+01,7.489745e+06,1.460023e+07
75%,9.399600e+05,0.000000e+00,0.000000e+00,NaN,NaN,1.307000e+02,1.099993e+07,2.190035e+07
max,2.251240e+06,3.621200e+04,2.367400e+04,NaN,NaN,9.999000e+02,1.430606e+07,2.920046e+07