# 🎮 SteamSense

# 04 - Feature Engineering

## Objective

Transform the cleaned Steam dataset into meaningful features that can be used by our recommendation engine.

---

## Goals

- Load cleaned datasets
- Create engineered features
- Convert datatypes
- Generate popularity metrics
- Prepare data for machine learning

---

## Output

A feature-rich dataset that will be used to build:

- Content-Based Recommendation System
- Collaborative Filtering
- Hybrid Recommendation Engine

In [24]:
import pandas as pd
import numpy as np

from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

In [25]:
DATA_PATH = Path("../data/processed")

In [26]:
games = pd.read_csv(DATA_PATH / "games_clean.csv")

In [27]:
games.head()

,app_id,title,date_release,win,mac,linux,rating,positive_ratio,user_reviews,price_final,price_original,discount,steam_deck
0,13500,Prince of Persia: Warrior Within™,2008-11-21,True,False,False,Very Positive,84,2199,9.99,9.99,0.0,True
1,22364,BRINK: Agents of Change,2011-08-03,True,False,False,Positive,85,21,2.99,2.99,0.0,True
2,113020,Monaco: What's Yours Is Mine,2013-04-24,True,True,True,Very Positive,92,3722,14.99,14.99,0.0,True
3,226560,Escape Dead Island,2014-11-18,True,False,False,Mixed,61,873,14.99,14.99,0.0,True
4,249050,Dungeon of the ENDLESS™,2014-10-27,True,True,False,Very Positive,88,8784,11.99,11.99,0.0,True

In [28]:
games.columns.tolist()

['app_id',
 'title',
 'date_release',
 'win',
 'mac',
 'linux',
 'rating',
 'positive_ratio',
 'user_reviews',
 'price_final',
 'price_original',
 'discount',
 'steam_deck']

In [29]:
print(f"Rows : {games.shape[0]:,}")
print(f"Columns : {games.shape[1]}")

Rows : 50,872
Columns : 13

In [30]:
games["date_release"] = pd.to_datetime(
    games["date_release"]
)

In [31]:
games["release_year"] = games["date_release"].dt.year

In [32]:
from datetime import datetime

CURRENT_YEAR = datetime.now().year

games["game_age"] = CURRENT_YEAR - games["release_year"]

In [33]:
games["is_free"] = (
    games["price_final"] == 0
).astype(int)

In [34]:
games["platform_count"] = (
    games["win"].astype(int)
    + games["mac"].astype(int)
    + games["linux"].astype(int)
)

In [35]:
games["steam_deck"] = games["steam_deck"].astype(int)

In [36]:
games["discount"] = games["discount"].astype(int)

In [37]:
games["popularity_score"] = (
    games["positive_ratio"] * 0.6
    + np.log1p(games["user_reviews"]) * 40
)

In [38]:
games["popularity_score"].describe()

count    50872.000000
mean       222.428181
std         74.853860
min         95.915811
25%        166.219769
50%        202.213922
75%        260.444509
max        685.986991
Name: popularity_score, dtype: float64

In [39]:
games.sort_values(
    by="popularity_score",
    ascending=False
)[
    [
        "title",
        "popularity_score",
        "positive_ratio",
        "user_reviews"
    ]
].head(10)

,title,popularity_score,positive_ratio,user_reviews
14398,Counter-Strike: Global Offensive,685.986991,88,7494460
13176,Dota 2,630.448635,82,2045628
12717,Grand Theft Auto V,620.013383,86,1484122
47770,PUBG: BATTLEGROUNDS,618.670715,57,2217226
13035,Terraria,608.490420,97,943413
47380,Team Fortress 2,607.849162,93,985819
14535,Tom Clancy's Rainbow Six® Siege,603.952044,86,993312
15363,Garry's Mod,603.894998,96,853733
13173,Rust,595.222514,87,786668
12800,The Witcher® 3: Wild Hunt,594.109034,96,668455

In [40]:
games["rating"].unique()

<StringArray>
[          'Very Positive',                'Positive',
                   'Mixed',         'Mostly Positive',
 'Overwhelmingly Positive',                'Negative',
         'Mostly Negative', 'Overwhelmingly Negative',
           'Very Negative']
Length: 9, dtype: str

In [41]:
games["rating"].value_counts()

rating
Positive                   13502
Very Positive              13139
Mixed                      12157
Mostly Positive             8738
Mostly Negative             1849
Overwhelmingly Positive     1110
Negative                     303
Very Negative                 60
Overwhelmingly Negative       14
Name: count, dtype: int64

In [42]:
games.isnull().sum()

app_id              0
title               0
date_release        0
win                 0
mac                 0
linux               0
rating              0
positive_ratio      0
user_reviews        0
price_final         0
price_original      0
discount            0
steam_deck          0
release_year        0
game_age            0
is_free             0
platform_count      0
popularity_score    0
dtype: int64

In [43]:
games.head()

,app_id,title,date_release,win,mac,linux,rating,positive_ratio,user_reviews,price_final,price_original,discount,steam_deck,release_year,game_age,is_free,platform_count,popularity_score
0,13500,Prince of Persia: Warrior Within™,2008-11-21,True,False,False,Very Positive,84,2199,9.99,9.99,0,1,2008,18,0,1,358.248506
1,22364,BRINK: Agents of Change,2011-08-03,True,False,False,Positive,85,21,2.99,2.99,0,1,2011,15,0,1,174.641698
2,113020,Monaco: What's Yours Is Mine,2013-04-24,True,True,True,Very Positive,92,3722,14.99,14.99,0,1,2013,13,0,3,384.091403
3,226560,Escape Dead Island,2014-11-18,True,False,False,Mixed,61,873,14.99,14.99,0,1,2014,12,0,1,307.523215
4,249050,Dungeon of the ENDLESS™,2014-10-27,True,True,False,Very Positive,88,8784,11.99,11.99,0,1,2014,12,0,2,416.032040

In [44]:
games.columns

Index(['app_id', 'title', 'date_release', 'win', 'mac', 'linux', 'rating',
       'positive_ratio', 'user_reviews', 'price_final', 'price_original',
       'discount', 'steam_deck', 'release_year', 'game_age', 'is_free',
       'platform_count', 'popularity_score'],
      dtype='str')

In [45]:
games.to_csv(
    DATA_PATH / "games_features.csv",
    index=False
)

In [46]:
print("✅ Feature Engineering Completed Successfully!")

✅ Feature Engineering Completed Successfully!

In [47]:
rating_map = {
    "Overwhelmingly Negative": 1,
    "Very Negative": 2,
    "Mostly Negative": 3,
    "Negative": 4,
    "Mixed": 5,
    "Positive": 6,
    "Mostly Positive": 7,
    "Very Positive": 8,
    "Overwhelmingly Positive": 9
}

In [48]:
games["rating_score"] = games["rating"].map(rating_map)

In [49]:
games[
    [
        "rating",
        "rating_score"
    ]
].head(15)

             rating  rating_score
0     Very Positive             8
1          Positive             6
2     Very Positive             8
3             Mixed             5
4     Very Positive             8
5     Very Positive             8
6   Mostly Positive             7
7             Mixed             5
8     Very Positive             8
9   Mostly Positive             7
10    Very Positive             8
11    Very Positive             8
12    Very Positive             8
13    Very Positive             8
14    Very Positive             8

In [50]:
games["rating_score"].isna().sum()

np.int64(0)

In [51]:
games.to_csv(
    DATA_PATH / "games_features.csv",
    index=False
)