In [1]:
import pandas as pd

from pathlib import Path

In [2]:
RAW_PATH = Path("../data/raw")
PROCESSED_PATH = Path("../data/processed")

In [3]:
metadata = pd.read_json(
    RAW_PATH / "games_metadata.json",
    lines=True
)

In [4]:
metadata.head()

,app_id,description,tags
0,13500,Enter the dark underworld of Prince of Persia ...,"[Action, Adventure, Parkour, Third Person, Gre..."
1,22364,,[Action]
2,113020,Monaco: What's Yours Is Mine is a single playe...,"[Co-op, Stealth, Indie, Heist, Local Co-Op, St..."
3,226560,Escape Dead Island is a Survival-Mystery adven...,"[Zombies, Adventure, Survival, Action, Third P..."
4,249050,Dungeon of the Endless is a Rogue-Like Dungeon...,"[Roguelike, Strategy, Tower Defense, Pixel Gra..."

In [5]:
metadata.info()

<class 'pandas.DataFrame'>
RangeIndex: 50872 entries, 0 to 50871
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   app_id       50872 non-null  int64
 1   description  50872 non-null  str
 2   tags         50872 non-null  object
dtypes: int64(1), object(1), str(1)
memory usage: 1.2+ MB

In [6]:
metadata.columns

Index(['app_id', 'description', 'tags'], dtype='str')

In [7]:
games = pd.read_csv(
    PROCESSED_PATH / "games_features.csv"
)

In [8]:
games = games.merge(
    metadata,
    on="app_id",
    how="left"
)

In [9]:
games.head()

,app_id,title,date_release,win,mac,linux,rating,positive_ratio,user_reviews,price_final,...,discount,steam_deck,release_year,game_age,is_free,platform_count,popularity_score,rating_score,description,tags
0,13500,Prince of Persia: Warrior Within™,2008-11-21,True,False,False,Very Positive,84,2199,9.99,...,0,1,2008,18,0,1,358.248506,8,Enter the dark underworld of Prince of Persia ...,"[Action, Adventure, Parkour, Third Person, Gre..."
1,22364,BRINK: Agents of Change,2011-08-03,True,False,False,Positive,85,21,2.99,...,0,1,2011,15,0,1,174.641698,6,,[Action]
2,113020,Monaco: What's Yours Is Mine,2013-04-24,True,True,True,Very Positive,92,3722,14.99,...,0,1,2013,13,0,3,384.091403,8,Monaco: What's Yours Is Mine is a single playe...,"[Co-op, Stealth, Indie, Heist, Local Co-Op, St..."
3,226560,Escape Dead Island,2014-11-18,True,False,False,Mixed,61,873,14.99,...,0,1,2014,12,0,1,307.523215,5,Escape Dead Island is a Survival-Mystery adven...,"[Zombies, Adventure, Survival, Action, Third P..."
4,249050,Dungeon of the ENDLESS™,2014-10-27,True,True,False,Very Positive,88,8784,11.99,...,0,1,2014,12,0,2,416.032040,8,Dungeon of the Endless is a Rogue-Like Dungeon...,"[Roguelike, Strategy, Tower Defense, Pixel Gra..."

In [10]:
games["tags"] = games["tags"].apply(
    lambda x: " ".join(x) if isinstance(x, list) else ""
)

In [11]:
games["description"] = (
    games["description"]
    .fillna("")
)

In [12]:
games["content"] = (
    games["title"] + " "
    + games["description"] + " "
    + games["tags"]
)

In [13]:
games.to_csv(
    PROCESSED_PATH / "games_content.csv",
    index=False
)